version: '2.1'

services:
  sftp:
    image: unocha/sftpd
    ports:
      - "0.0.0.0:2223:22"
    environment:
      SFTP_USER: user
      SFTP_PASS: pass
      #SFTP_KEY: 'public key'
      #SFTP_PASS_AUTH: 'no'
      SFTP_PASS_AUTH: 'yes'
      SFTP_HOME: /srv/sftp
