FROM unocha/alpine-base-s6:%%UPSTREAM%%

# Parse arguments for the build command.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="base-s6" \
      org.label-schema.description="This service provides a base SFTPd Alpine Linux container." \
      org.label-schema.architecture="x86_64" \
      org.label-schema.distribution="Alpine Linux" \
      org.label-schema.distribution-version=$VERSION

ENV SCP_USER=user \
    SCP_PASS=pass \
    SCP_PKEY=garblegarblegarble \
    SCP_PASS_AUTH=no \
    SCP_HOME=/srv/user

COPY run_scp /tmp/

RUN apk add --update-cache \
        openssh-sftp-server \
        dropbear && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /etc/dropbear /etc/services.d/scp && \
    mv /tmp/run_scp /etc/services.d/scp/run

EXPOSE 22
