#!/usr/bin/with-contenv sh

adduser -h ${SFTP_HOME} -D ${SFTP_USER}
echo "${SFTP_USER}:${SFTP_PASS}" | chpasswd

mkdir -p /etc/dropbear ${SFTP_HOME}/.ssh

echo "${SFTP_PUBKEY}" > ${SFTP_HOME}/.ssh/authorized_keys

chown -R ${SFTP_USER} ${SFTP_HOME}
chmod 700 ${SFTP_HOME}/.ssh
chmod 600 ${SFTP_HOME}/.ssh/authorized_keys

touch /var/log/lastlog

EXTRA_OPTIONS=""
if [ "${SFTP_PASS_AUTH}" == "no" ]; then
    EXTRA_OPTIONS="-s"
fi

exec dropbear -RFEmwgjk $EXTRA_OPTIONS -p 22
