FROM public.ecr.aws/unocha/base-php:%%UPSTREAM%%

MAINTAINER UN-OCHA Operations <ops+docker@humanitarianresponse.info>

# Thanks to orakili <docker@orakili.net>

# A little bit of metadata management.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE
ENV WP_RELEASE=2.5.0 \
    PAGER=more

LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.name="php" \
      org.label-schema.description="This service provides a php-fpm platform with composer and wp-cli." \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      info.humanitarianresponse.php=$VERSION \
      info.humanitarianresponse.php.modules="apc bcmath bz2 calendar ctype curl dom exif fileinfo fpm ftp gd geos gettext iconv igbinary imagick imap intl json mcrypt memcached opcache openssl pdo pdo_mysql phar posix redis shmop soap sysvmsg sysvsem sysvshm simplexml sockets xml xmlreader xmlwriter xsl yaml zip zlib" \
      info.humanitarianresponse.php.sapi="fpm" \
      info.humanitarianresponse.composer="2.1.3" \
      info.humanitarianresponse.wp=$WP_RELEASE

COPY etc/my.cnf.d/client.cnf /client.cnf

RUN apk add --update-cache \
        git \
        patch \
        php7 \
        mysql-client && \
    rm -rf /var/cache/apk/* && \
    \
    # Configure the MySQL client library.
    mv -f /client.cnf /etc/my.cnf.d/client.cnf && \
    \
    # Install composer, as suggested by https://getcomposer.org/
    # and https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
    COMPOSER_HASH=$(curl -sS https://composer.github.io/installer.sig) && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('SHA384', 'composer-setup.php') === '$COMPOSER_HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php --install-dir=/usr/bin --filename=composer && \
    php -r "unlink('composer-setup.php');" && \
    # Install wp-cli and symlink it somewhere useful.
    COMPOSER_HOME=/usr/local/wp$WP_RELEASE  \
      composer global require \
        wp-cli/wp-cli:$WP_RELEASE \
        wp-cli/extension-command \
        wp-cli/maintenance-mode-command \
        wp-cli/core-command \
        wp-cli/db-command \
        wp-cli/search-replace-command && \
    ln -sf /usr/local/wp$WP_RELEASE/vendor/wp-cli/wp-cli/bin/wp /usr/bin/wp && \
    wp --info && \
    # Clear the cache to reduce the layer size.
    rm -rf /var/cache/apk/*
