FROM public.ecr.aws/unocha/alpine-base:%%UPSTREAM%%

# Parse arguments for the build command.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="base-s6" \
      org.label-schema.description="This service provides a base Alpine Linux container." \
      org.label-schema.architecture="x86_64" \
      org.label-schema.distribution="Alpine Linux" \
      org.label-schema.distribution-version=$UPSTREAM

RUN apk add --no-cache --purge -uU curl && \
    S6VERSION=$(curl -sSL https://api.github.com/repos/just-containers/s6-overlay/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]' | sed -e 's_v__') && \
    S6ARCH=$(uname -m | sed 's/x86_64/amd64/') && \
    echo "Installing s6 version: $S6VERSION for $S6ARCH" && \
    curl -o /tmp/s6-overlay.tar.gz -jkSL https://github.com/just-containers/s6-overlay/releases/download/v${S6VERSION}/s6-overlay-${S6ARCH}.tar.gz && \
    tar xzf /tmp/s6-overlay.tar.gz -C / && \
    rm -rf /var/cache/apk/* /tmp/*

ENTRYPOINT ["/init"]

CMD []
