FROM public.ecr.aws/unocha/alpine-base:%%UPSTREAM%%

# Parse arguments for the build command.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

ENV S6VERSION=2.2.0.3

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="base-s6" \
      org.label-schema.version=$VERSION \
      org.label-schema.description="This image provides a s6-init base Alpine Linux container." \
      org.label-schema.s6-version=$S6VERSION

RUN S6ARCH=$(uname -m | sed 's/x86_64/amd64/') && \
    echo "Installing s6 version: $S6VERSION for $S6ARCH" && \
    curl -o /tmp/s6-overlay.tar.gz -jkSL https://github.com/just-containers/s6-overlay/releases/download/v${S6VERSION}/s6-overlay-${S6ARCH}.tar.gz && \
    tar xzf /tmp/s6-overlay.tar.gz -C / && \
    rm -f tar xzf /tmp/s6-overlay.tar.gz

ENTRYPOINT ["/init"]

CMD []
