FROM node:%%UPSTREAM%%

# Parse arguments for the build command.
ARG NODE_VERSION=8.11.2
ARG NPM_VERSION=5.6.0
ARG YARN_VERSION=1.6.0
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE
ARG S6_VERSION=v2.2.0.3

ENV NODE_VERSION=$NODE_VERSION \
    YARN_VERSION=$YARN_VERSION \
    NPM_VERSION=$NPM_VERSION \
    NODE_APP_DIR=/srv/www \
    NODE_PATH=/usr/lib/node_modules:/usr/local/lib/node_modules:/usr/local/share/.config/yarn/global/node_modules \
    SRC_DIR=/src \
    NEW_RELIC_HOME=/srv/ \
    NEW_RELIC_LOG_LEVEL=info \
    NEW_RELIC_LICENSE_KEY=aaa \
    NEW_RELIC_APP_NAME=nodeapp \
    NEW_RELIC_NO_CONFIG_FILE=True \
    APPUSER_GID=4000 \
    APPUSER_UID=4000 \
    DEBIAN_FRONTEND=noninteractive \
    TERM=xterm


# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="nodejs-base" \
      org.label-schema.description="This service provides a base nodejs platform." \
      org.label-schema.architecture="x86_64" \
      org.label-schema.distribution="NodeJS official image" \
      org.label-schema.distribution-version="%%UPSTREAM%%" \
      info.humanitarianresponse.nodejs="$NODE_VERSION" \
      info.humanitarianresponse.npm="$NPM_VERSION" \
      info.humanitarianresponse.yarn="$YARN_VERSION"

RUN set -x && \
    apt-get -qy update && \
    apt-get -qy install \
      curl \
      nano && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /src/*.deb && \
    yarn global add \
      grunt-cli \
      newrelic && \
    mkdir -p /tmp && \
    chmod 1777 /tmp && \
    mkdir -p ${SRC_DIR} ${NODE_APP_DIR} && \
    cp -a /usr/local/share/.config/yarn/global/node_modules/newrelic/newrelic.js /srv  && \
    curl -sL https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-amd64.tar.gz -o /tmp/s6.tgz && \
    tar xzf /tmp/s6.tgz -C / && \
    rm -f /tmp/s6.tgz && \
    groupadd --system -g $APPUSER_GID appuser && \
    useradd --system -u $APPUSER_UID -s /sbin/nologin -c 'Docker App User' \
      -d /home/appuser -g appuser -m appuser

ENTRYPOINT []

CMD []
