FROM public.ecr.aws/unocha/nodejs-builder:%%UPSTREAM%%

MAINTAINER UN-OCHA Operations <ops+docker@humanitarianresponse.info>

# Alpine based docker image.
# Includes php composer, ruby bundler, less, npm, jasmine, compass and drush.

# Parse arguments for the build command.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="unified-builder" \
      org.label-schema.description="This service provides a builder container for PHP, with node and sass helpers." \
      org.label-schema.architecture="x86_64" \
      org.label-schema.distribution="Alpine Linux" \
      org.label-schema.distribution-version="3.15" \
      info.humanitarianresponse.php=$VERSION \
      info.humanitarianresponse.php.modules="bcmath bz2 calendar ctype curl dom exif fileinfo fpm ftp gd gettext gmp iconv igbinary imagick imap intl json mcrypt memcached opcache openssl pdo pdo_mysql phar posix redis shmop soap sodium sysvmsg sysvsem sysvshm simplexml sockets xml xmlreader xmlwriter xsl zip zlib" \
      info.humanitarianresponse.php.sapi="cli" \
      info.humanitarianresponse.composer="2.1.5" \
      info.humanitarianresponse.node="12.18" \
      info.humanitarianresponse.npm="12.18" \
      info.humanitarianresponse.yarn="1.7.0" \
      info.humanitarianresponse.compass="3.2.0" \
      info.humanitarianresponse.jasmine="3.4.0" \
      info.humanitarianresponse.python="3.8.5" \
      info.humanitarianresponse.ruby="2.3.7"

COPY drushrc.php /drushrc.php
COPY etc/php8/php.ini /tmp/php.ini

RUN npm install --location=global npm@latest && \
    npm install --location=global \
      jasmine && \
    rm -rf /tmp/npm-* && \
    \
    apk add --update-cache \
      bash \
      ca-certificates \
      curl \
      build-base \
      git \
      gzip \
      openssh-client \
      patch \
      python3 \
      rsync \
      tar \
      wget \
      php8-bcmath \
      php8-bz2 \
      php8-calendar \
      php8-ctype \
      php8-curl \
      php8-dom \
      php8-exif \
      php8-iconv \
      php8-fileinfo \
      php8-ftp \
      php8-gd \
      php8-gettext \
      php8-gmp \
      php8-iconv \
      php8-imap \
      php8-intl \
      php8-json \
      php8-mbstring \
      php8-mysqli \
      php8-opcache \
      php8-openssl \
      php8-pdo \
      php8-pdo_mysql \
      php8-phar \
      php8-posix \
      php8-redis \
      php8-shmop \
      php8-sodium \
      php8-sysvmsg \
      php8-sysvsem \
      php8-sysvshm \
      php8-simplexml \
      php8-soap \
      php8-sockets \
      php8-tokenizer \
      php8-xml \
      php8-xmlreader \
      php8-xmlwriter \
      php8-xsl \
      php8-zip \
      php8-zlib \
      php8-pecl-imagick \
      php8-pecl-mcrypt \
      php8-pecl-memcached && \
    rm -rf /var/cache/apk/* && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    cd /tmp && \
    mv /tmp/php.ini /etc/php8/php.ini && \
    ln -sf /usr/bin/php8 /usr/bin/php && \
    COMPOSER_HASH=$(curl -sS https://composer.github.io/installer.sig) && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('SHA384', 'composer-setup.php') === '$COMPOSER_HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php --install-dir=/usr/bin --filename=composer && \
    php -r "unlink('composer-setup.php');" && \
    # Add dependencies for capsper and phantom, but do NOT install them. npm will fetch a newer one anyway.
    apk add --update-cache \
      fontconfig \
      libc6-compat && \
    rm -rf /var/cache/apk/*

WORKDIR /tmp

CMD ["bash"]
