#!/usr/bin/with-contenv sh

DATADIR=/var/lib/openldap/openldap-data
CONFDIR=/etc/openldap/conf.d

# no conf yet? lets create it.
if [ "$(find $CONFDIR -maxdepth 1 -iname '*.conf' | wc -l)" == "0" ]; then
    if [ "$REPLICATE" == "yes" ]; then
        sed -i 's|.*syncrepl.conf$|include /etc/openldap/conf.d/syncrepl.conf|' /etc/openldap/slapd.tpl
    else
        sed -i 's|.*syncrepl.conf$|#include /etc/openldap/conf.d/syncrepl.conf|' /etc/openldap/slapd.tpl
    fi
    
    if [ "$LDAPS" == "yes" ]; then
        sed -i 's|.*ssl.conf$|include /etc/openldap/conf.d/ssl.conf|' /etc/openldap/slapd.tpl
    else
        sed -i 's|.*ssl.conf$|#include /etc/openldap/conf.d/ssl.conf|' /etc/openldap/slapd.tpl
    fi

    MNGRPASS=$(slappasswd -s $MNGRPASS) \
        envsubst '$DOMAIN $SUFFIX $MNGRPASS $REPLPASS $SID' \
        < /etc/openldap/slapd.tpl > $CONFDIR/slapd.conf
    envsubst \
        < /etc/openldap/ssl.tpl > $CONFDIR/ssl.conf
    envsubst '$DOMAIN $SUFFIX $REPLPASS $REMOTE $SID' \
        < /etc/openldap/syncrepl.tpl > $CONFDIR/syncrepl.conf
fi

# no data yet? lets add some.
if [ "$(find $DATADIR -maxdepth 1 ! -path $DATADIR | wc -l)" == "0" ]; then
    MNGRPASS=$(slappasswd -s $MNGRPASS) \
    REPLPASSCRYPT=$(slappasswd -s $REPLPASS) \
        envsubst '$DOMAIN $SUFFIX $MNGRPASS $REPLPASS $REPLPASSCRYPT $SID' \
        < /etc/openldap/base.ldif.tpl > $CONFDIR/base.ldif
    JOHNPASS=$(slappasswd -s $JOHNPASS) \
        envsubst '$DOMAIN $SUFFIX $JOHNPASS' \
        < /etc/openldap/john.ldif.tpl > $CONFDIR/john.ldif
    echo -e '\nAdding the base skeleton of your ldap org...'
    # echo '  ldapadd -D "cn=Manager,dc=$DOMAIN,dc=$SUFFIX" -w $MNGRPASS -f /etc/openldap/conf.d/base.ldif'
    s6-setuidgid ldap slapadd -l /etc/openldap/conf.d/base.ldif -f /etc/openldap/slapd-init.conf -d 12
    echo 'Done.'
    echo -e '\nAdding a John Doe entry:'
    s6-setuidgid ldap slapadd -l /etc/openldap/conf.d/john.ldif -f /etc/openldap/slapd-init.conf -d 12
    echo 'Done.'
    echo 'Search with:'
    echo -e '  ldapsearch -x -b "dc=$DOMAIN,dc=$SUFFIX" "(objectclass=*)"\n'
    echo 'Have fun!'
    cp -a /etc/openldap/DB_CONFIG.example /var/lib/openldap/openldap-data/DB_CONFIG

fi

exec /usr/sbin/slapd -u ldap -g ldap -f /etc/openldap/slapd-init.conf -h "ldap:/// ldaps:///" $EXTRA_OPTIONS
