#!/usr/bin/with-contenv sh


mkdir -p ${PGDATA}

# taken care of in initialization
#chown -R postgres:postgres ${PGDATA}

test "$(ls -A "$PGDATA" 2>/dev/null)" || exec s6-setuidgid postgres /usr/bin/initdb -D $PGDATA

# add md5 auth option for clients
[ $(grep -cE "host(\s)+all(\s)+all(\s)+0.0.0.0/0(\s)+md5" $PGDATA/pg_hba.conf) -eq 1 ] || \
  echo "host all all 0.0.0.0/0 md5" >> $PGDATA/pg_hba.conf

args=""
[ -z ${PG_CONFIG_FILE} ] || args="--config-file=${PG_CONFIG_FILE}"

exec s6-setuidgid postgres /usr/bin/postgres -h 0.0.0.0 -D ${PGDATA} $args
