FROM docker.elastic.co/elasticsearch/elasticsearch:%%UPSTREAM%%

# Parse arguments for the build command.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="base" \
      org.label-schema.version=$VERSION \
      org.label-schema.description="This image provides an ElasticSearch Linux container." \
      org.label-schema.architecture="x86_64,aarch64" \
      org.label-schema.distribution="Debian Linux" \
      org.label-schema.distribution-version=$VERSION


RUN elasticsearch-plugin install --batch analysis-icu
