FROM public.ecr.aws/unocha/alpine-base:%%UPSTREAM%%

# Parse arguments for the build command.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="nginx" \
      org.label-schema.description="This service provides a base nginx platform." \
      org.label-schema.architecture="x86_64" \
      org.label-schema.distribution="Alpine Linux" \
      org.label-schema.distribution-version="%%UPSTREAM%%" \
      info.humanitarianresponse.nginx=$VERSION

COPY default.conf env.conf index.html /tmp/

# Install nginx.
RUN apk update && \
    apk upgrade && \
    apk add \
      nginx \
      nginx-mod-http-upload-progress \
      nginx-mod-http-lua \
      nginx-mod-http-echo \
      nginx-mod-http-cache-purge \
      nginx-mod-http-fancyindex \
      nginx-mod-http-headers-more && \
    rm -rf /var/cache/apk/* && \
    mkdir -p  /etc/nginx/env /run/nginx /srv/www/html /var/log/nginx /var/cache/nginx && \
    sed -i 's/access_log.*/access_log off;/' /etc/nginx/nginx.conf && \
    mv /tmp/default.conf /etc/nginx/http.d/default.conf && \
    mv /tmp/env.conf /etc/nginx/env/env.conf && \
    mv /tmp/index.html /srv/www/html/index.html && \
    # sed -i "s|^http {|http {\n\t#proxy_cookie_path off;\n|" /etc/nginx/nginx.conf && \
    # sed -i "s|^http {|http {\n\t# disable it by adding the following line to the desired server or location block|" /etc/nginx/nginx.conf && \
    # sed -i "s|^http {|http {\n\tproxy_cookie_path ~^/(.*)$ \"/\$1; SameSite=Lax\";|" /etc/nginx/nginx.conf && \
    # sed -i "s|^http {|http {\n\t# add SameSite to cookies|" /etc/nginx/nginx.conf && \
    # sed -i "s|^http {|http {\n\tmore_set_headers \"Content-Security-Policy: default-src 'self'\";|" /etc/nginx/nginx.conf && \
    # sed -i "s|^http {|http {\n\tmore_set_headers 'Referrer-Policy: strict-origin-when-cross-origin';|" /etc/nginx/nginx.conf && \
    sed -i "s|^http {|http {\n\tmore_set_headers 'X-Content-Type-Options: nosniff';\n|" /etc/nginx/nginx.conf && \
    sed -i "s|^http {|http {\n\tmore_set_headers 'X-XSS-Protection: 1; mode=block';|" /etc/nginx/nginx.conf && \
    sed -i "s|^http {|http {\n\tmore_set_headers 'X-Frame-Options: SAMEORIGIN';|" /etc/nginx/nginx.conf && \
    sed -i "s|^http {|http {\n\tmore_set_headers 'Strict-Transport-Security: max-age=31536000; includeSubDomains; preload; always;';|" /etc/nginx/nginx.conf && \
    sed -i "s|^http {|http {\n\tmore_set_headers 'Server: \$http_host';|" /etc/nginx/nginx.conf && \
    sed -i "s|^http {|http {\n\n\t# add global headers|"  /etc/nginx/nginx.conf && \
    sed -i "s|^\tmap \$http_upgrade|\t# map \$http_upgrade|" /etc/nginx/nginx.conf && \
    sed -i "s|^\t\tdefault upgrade;|\t#\tdefault upgrade;|" /etc/nginx/nginx.conf && \
    sed -i "s|^\t\t'' close;|\t#\t'' close;|" /etc/nginx/nginx.conf && \
    sed -i "s|^\t}|\t# }|" /etc/nginx/nginx.conf && \
    echo "include /etc/nginx/env/*.conf;" >> /etc/nginx/nginx.conf

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]

# Volumes
# - Conf: /etc/nginx/http.d (default.conf)
# - Logs: /var/log/nginx
# - Data: /srv/www/html
# - Cache: /var/cache/nginx
