FROM unocha/alpine-base:%%UPSTREAM%%

# Parse arguments for the build command.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="nginx" \
      org.label-schema.description="This service provides a base nginx platform." \
      org.label-schema.architecture="x86_64" \
      org.label-schema.distribution="Alpine Linux" \
      org.label-schema.distribution-version="%%UPSTREAM%%" \
      info.humanitarianresponse.nginx=$VERSION

COPY default.conf env.conf index.html /tmp/

# Install nginx.
RUN apk update && \
    apk upgrade && \
    apk add \
      nginx \
      nginx-mod-http-upload-progress \
      nginx-mod-http-lua \
      nginx-mod-http-echo \
      nginx-mod-http-cache-purge \
      nginx-mod-http-fancyindex && \
    rm -rf /var/cache/apk/* && \
    mkdir -p  /etc/nginx/env /run/nginx /srv/www/html /var/log/nginx /var/cache/nginx && \
    sed -i 's/access_log.*/access_log off;/' /etc/nginx/nginx.conf && \
    mv /tmp/default.conf /etc/nginx/http.d/default.conf && \
    mv /tmp/env.conf /etc/nginx/env/env.conf && \
    mv /tmp/index.html /srv/www/html/index.html && \
    echo "include /etc/nginx/env/*.conf;" >> /etc/nginx/nginx.conf && \
    sed -i "s|^\tmap \$http_upgrade|\t# map \$http_upgrade|" /etc/nginx/nginx.conf && \
    sed -i "s|^\t\tdefault upgrade;|\t#\tdefault upgrade;|" /etc/nginx/nginx.conf && \
    sed -i "s|^\t\t'' close;|\t#\t'' close;|" /etc/nginx/nginx.conf && \
    sed -i "s|^\t}|\t# }|" /etc/nginx/nginx.conf

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]

# Volumes
# - Conf: /etc/nginx/conf.d (default.conf)
# - Logs: /var/log/nginx
# - Data: /srv/www/html
# - Cache: /var/cache/nginx
