ARG VERSION=%%VERSION%%
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
# ARG VERSION

FROM golang:1.25-alpine%%UPSTREAM%% AS build

ARG WORKDIR=/go/src/github.com/google/cadvisor

WORKDIR $WORKDIR

# Install build depdencies for all supported arches
RUN apk --no-cache add \
        bash \
        build-base \
        cmake \
        device-mapper \
        findutils \
        git \
        libc6-compat \
        linux-headers \
        ndctl-dev \
        pkgconfig \
        python3 \
        wget \
        zfs && \
    apk --no-cache add thin-provisioning-tools && \
    echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf && \
    rm -rf /var/cache/apk/* && \
    cd /tmp && \
    wget https://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.13.0.tar.gz && \
    echo "bcb52090f02bc7bcb5ac066494cd55bbd5084e65  libpfm-4.13.0.tar.gz" | sha1sum -c  && \
    tar -xzf libpfm-4.13.0.tar.gz && \
    rm libpfm-4.13.0.tar.gz && \
    export DBG="-g -Wall" && \
    make -e -C libpfm-4.13.0 && \
    make install -C libpfm-4.13.0 && \
    cd $WORKDIR && \
    git clone https://github.com/google/cadvisor.git . && \
    git switch v$VERSION -- detach && \
    cd cmd && go mod download && cd .. && \
    export GO_TAGS="libpfm,netgo"; \
    # if [ "$(uname --machine)" = "x86_64" ]; then \
    #       # Disable libipmctl due to https://github.com/google/cadvisor/issues/3482
    #       #export GO_TAGS="$GO_TAGS,libipmctl"; \
    #       export GO_TAGS="$GO_TAGS"; \
    # fi; \
    GO_FLAGS="-tags=$GO_TAGS" ./build/build.sh

# ipmctl only supports Intel x86_64 processors.
# https://github.com/intel/ipmctl/issues/163

# Disable libipmctl due to https://github.com/google/cadvisor/issues/3482
#RUN if [ "$(uname --machine)" = "x86_64" ]; then \
    #git clone -b v02.00.00.3885 https://github.com/intel/ipmctl/ && \
    #cd ipmctl && \
    #mkdir output && \
    #cd output && \
    #cmake -DRELEASE=ON -DCMAKE_INSTALL_PREFIX=/ -DCMAKE_INSTALL_LIBDIR=/usr/local/lib .. && \
    #make -j all && \
    #make install; fi

# FROM mirror.gcr.io/library/alpine:3.18
FROM alpine:%%UPSTREAM%%

RUN apk --no-cache add libc6-compat device-mapper findutils ndctl thin-provisioning-tools zfs && \
    echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf && \
    rm -rf /var/cache/apk/*

# Grab cadvisor,libpfm4 and libipmctl from "build" container if they exist (libipmctl only works on amd64/x86_64).
COPY --from=build /usr/local/lib/libpfm.so* /usr/local/lib/
COPY --from=build /usr/local/lib/libipmctl.so* /usr/local/lib/
COPY --from=build /go/src/github.com/google/cadvisor/_output/cadvisor /usr/bin/cadvisor

EXPOSE 8080

ENV CADVISOR_HEALTHCHECK_URL=http://localhost:8080/healthz

HEALTHCHECK --interval=30s --timeout=3s \
  CMD wget --quiet --tries=1 --spider $CADVISOR_HEALTHCHECK_URL || exit 1

ENTRYPOINT ["/usr/bin/cadvisor", "-logtostderr"]
