include ../../../Makefile.conf
include ../../../Makefile.buildx.conf
include ../Makefile.conf

UPSTREAM=$$(UPSTREAM)
VERSION=$$(VERSION)
IMAGE=base-php

all: buildx tagx

mrproper: clean_images clean
