FROM alpine:%%UPSTREAM%%


# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="postgis" \
      org.label-schema.description="This service provides a generic tool to do all kinds of opsy things like db dumps etc" \
      org.label-schema.architecture="x86_64" \
      org.label-schema.distribution="Alpine Linux" \
      org.label-schema.distribution-version="%%UPSTREAM%%"

RUN apk update && \
    apk upgrade && \
    apk add \
        git \
        mongo-tools \
        mysql-client \
        postgresql-client \
        rsync && \
    rm -rf /var/cache/apk/*

CMD [sh]
