FROM public.ecr.aws/unocha/php-k8s:%%UPSTREAM%%

# A little bit of metadata management.
ARG VERSION
ARG UPSTREAM
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

ENV PHP_NEWRELIC_ENABLED=1

LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.name="php-k8s" \
      org.label-schema.description="This service provides an nginx / php-fpm platform with New Relic, composer and wp-cli." \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      info.humanitarianresponse.nginx=$UPSTREAM \
      info.humanitarianresponse.php=$VERSION \
