FROM unocha/base-php7:%%UPSTREAM%%

MAINTAINER UN-OCHA Operations <ops+docker@humanitarianresponse.info>

# Thanks to orakili <docker@orakili.net>

# A little bit of metadata management.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.name="php7" \
      org.label-schema.description="This service provides a php-fpm platform with drush and composer." \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF

ENV DRUSH_VERSION=8 \
    DRUSH_RELEASE=8.x-dev

COPY drushrc.php /drushrc.php
COPY drush8-2282.patch /tmp/drush8-2282.patch
COPY drush8-2567.patch /tmp/drush8-2567.patch

RUN apk add --update-cache \
        git \
        php7 \
        mysql-client \
        postgresql-client  && \
    rm -rf /var/cache/apk/* && \
    # Set unlimited memory for CLI php.
    sed -i 's/^memory_limit = .*/memory_limit = -1/' /etc/php7/php.ini && \
    # Install composer, as suggested by https://getcomposer.org/
    # and https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
    COMPOSER_HASH=$(curl -sS https://composer.github.io/installer.sig) && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('SHA384', 'composer-setup.php') === '$COMPOSER_HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php --install-dir=/usr/bin --filename=composer && \
    php -r "unlink('composer-setup.php');" && \
    # Install drush and symlink it somewhere useful.
    COMPOSER_HOME=/usr/local/drush$DRUSH_VERSION \
      composer global require drush/drush:$DRUSH_RELEASE && \
    cd /usr/local/drush8/vendor/drush/drush && \
      patch -p1 -i /tmp/drush8-2282.patch && \
      patch -p1 -i /tmp/drush8-2567.patch && \
    cd / && \
    ln -sf /usr/local/drush$DRUSH_VERSION/vendor/bin/drush /usr/bin/drush && \
    drush status && \
    # Install registry_rebuild to the appuser's homedir.
    drush -y @none dl --destination=/home/appuser/.drush/commands registry_rebuild-7.x && \
    # Ensure the appuser's drush directory is writable.
    chown -R appuser:appuser /home/appuser/.drush && \
    # Symlink the appuser's drush module to root's.
    mkdir -p /root/.drush && \
    ln -s /home/appuser/.drush/commands /root/.drush/commands && \
    # Add our default drushrc.php file.
    mkdir -p /etc/drush && \
    mv /drushrc.php /etc/drush/drushrc.php && \
    # Cleanup.
    rm -f /tmp/drush8-2282.patch /tmp/drush8-2567.patch

VOLUME ["/etc/php7"]

# Volumes
# - Conf: /etc/php7/ (php.ini, php-fpm.conf, conf.d/)
# - Logs: /var/log/php
# - Data: /srv/www, /var/lib/php/session
