FROM public.ecr.aws/unocha/alpine-base-s6:%%UPSTREAM%%

# Parse arguments for the build command.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name="python3-base-s6" \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.description="This image provides a base Python Alpine Linux container with S6-init as entrypoint."

RUN apk add --update-cache \
      python3 \
      py3-pip && \
    rm -rf /var/cache/apk/*
