FROM unocha/alpine-base-nodejs:%%UPSTREAM%%

MAINTAINER Serban Teodorescu <teodorescu.serban@gmail.com>

# Parse arguments for the build command.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="alpine-nodejs-builder" \
      org.label-schema.description="This service provides a builder container for node." \
      org.label-schema.architecture="x86_64" \
      org.label-schema.distribution="Alpine Linux" \
      org.label-schema.distribution-version="3.12" \
      info.humanitarianresponse.node="12.18.2" \
      info.humanitarianresponse.npm="12.18.2" \
      info.humanitarianresponse.ruby="2.7.1-r3"

ENV DST_DIR=/dst

ENTRYPOINT []

RUN apk update && \
    apk upgrade && \
    apk add \
        rsync \
        ruby-bundler \
        build-base \
        ruby-dev \
        libffi-dev && \
    gem install --no-document \
        bootstrap-sass \
        font-awesome-sass \
        sass-globbing \
        compass && \
    mkdir -p /root/.npm && \
    npm install -g \
        less \
        karma && \
    apk del \
        build-base \
        ruby-dev \
        libffi-dev && \
    rm -rf /var/cache/apk/* /root/.npm

# inherits also as volumes SRC_DIR=/src and $NODE_APP_DIR=/srv/www
VOLUME ["${DST_DIR}"]
