include ../../../Makefile.conf
include ../../Makefile.conf

UPSTREAM=$$(UPSTREAM))
VERSION=$$(VERSION))

IMAGE=alpine-php-fpm-drupal8-ghosts-puppeteer

all: template build tag clean_images

mrproper: clean_images clean
