FROM unocha/nodejs-base:%%UPSTREAM%%

# Parse arguments for the build command.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="alpine-nodejs-builder" \
      org.label-schema.description="This service provides a builder container for node." \
      org.label-schema.architecture="x86_64" \
      org.label-schema.distribution="Alpine Linux" \
      org.label-schema.distribution-version="3.12" \
      info.humanitarianresponse.nodejs="$NODE_VERSION" \
      info.humanitarianresponse.npm="$NPM_VERSION" \
      info.humanitarianresponse.yarn="$YARN_VERSION" \
      info.humanitarianresponse.ruby="2.5.5-r0"

ENV DST_DIR=/dst

ENTRYPOINT []

RUN apk update && \
    apk upgrade && \
    apk add \
        rsync \
        ruby-bundler \
        ruby-rake-compiler \
        build-base \
        ruby-dev \
        libffi-dev && \
    gem install --no-document \
        bootstrap-sass \
        font-awesome-sass \
        sass-globbing \
        compass && \
    yarn global add \
        less \
        karma && \
    yarn cache clean && \
    apk del \
        build-base \
        ruby-dev \
        libffi-dev && \
    rm -rf /var/cache/apk/*

# inherits also as volumes SRC_DIR=/src and $NODE_APP_DIR=/srv/www
# we'd better NOT expose this as a volume, unless we really intend mapping to a host folder
# in which case we can just skip exposing it.
# VOLUME ["${DST_DIR}"]
