FROM node:%%UPSTREAM%%

# Parse arguments for the build command.
ARG NODE_VERSION=10.24.0
ARG NPM_VERSION=6.14.11
ARG YARN_VERSION=1.22.10
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

ENV NODE_VERSION=$NODE_VERSION \
    YARN_VERSION=$YARN_VERSION \
    NPM_VERSION=$NPM_VERSION \
    NODE_APP_DIR=/srv/www \
    NODE_PATH=/usr/lib/node_modules:/usr/local/lib/node_modules:/usr/local/share/.config/yarn/global/node_modules \
    SRC_DIR=/src \
    NEW_RELIC_HOME=/srv/ \
    NEW_RELIC_LOG_LEVEL=info \
    NEW_RELIC_LICENSE_KEY=aaa \
    NEW_RELIC_APP_NAME=nodeapp \
    NEW_RELIC_NO_CONFIG_FILE=True \
    APPUSER_GID=4000 \
    APPUSER_UID=4000

#     NPM_CONFIG_SPIN=false \
#     NPM_CONFIG_PROGRESS=false \

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="nodejs-base" \
      org.label-schema.description="This service provides a base nodejs platform." \
      org.label-schema.architecture="x86_64" \
      org.label-schema.distribution="NodeJS official image" \
      org.label-schema.distribution-version="%%UPSTREAM%%" \
      info.humanitarianresponse.nodejs="$NODE_VERSION" \
      info.humanitarianresponse.npm="$NPM_VERSION" \
      info.humanitarianresponse.yarn="$YARN_VERSION"

RUN set +x && apk update && \
    apk upgrade && \
    apk add --no-cache \
      libstdc++ && \
    apk add --no-cache \
      shadow \
      curl \
      git && \
    yarn global add \
      grunt-cli \
      newrelic && \
    yarn cache clean && \
    S6VERSION=$(curl -sL https://api.github.com/repos/just-containers/s6-overlay/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]' | sed -e 's_v__') && \
    S6ARCH=$(uname -m) && \
    echo "Installing s6 version: $S6VERSION for $S6ARCH" && \
    curl -o /tmp/s6-overlay-noarch.tar.xz -jkSL  https://github.com/just-containers/s6-overlay/releases/download/v${S6VERSION}/s6-overlay-noarch-${S6VERSION}.tar.xz && \
    tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz && \
    curl -o /tmp/s6-overlay.tar.xz -jkSL  https://github.com/just-containers/s6-overlay/releases/download/v${S6VERSION}/s6-overlay-x86_64-${S6VERSION}.tar.xz && \
    tar -C / -Jxpf /tmp/s6-overlay.tar.xz && \
    rm -rf /var/cache/apk/* /tmp/* && \
    rm -rf \
      /usr/lib/node_modules/npm/man \
      /usr/lib/node_modules/npm/doc \
      /usr/lib/node_modules/npm/html \
      /usr/lib/node_modules/npm/scripts \
      /tmp && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /tmp && \
    chmod 1777 /tmp && \
    mkdir -p ${SRC_DIR} ${NODE_APP_DIR} && \
    cp -a /usr/local/share/.config/yarn/global/node_modules/newrelic/newrelic.js /srv && \
    groupadd --system -g $APPUSER_GID appuser && \
    useradd --system -u $APPUSER_UID -s /sbin/nologin -c 'Docker App User' \
      -d /home/appuser -g appuser -m appuser

ENTRYPOINT []

CMD []
