FROM unocha/alpine-base-s6:%%UPSTREAM%%

# Parse arguments for the build command.
ARG NODE_VERSION=10.24.0
ARG NPM_VERSION=6.14.11
ARG YARN_VERSION=1.22.10
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

ENV NODE_VERSION=$NODE_VERSION \
    YARN_VERSION=$YARN_VERSION \
    NPM_VERSION=$NPM_VERSION \
    NODE_APP_DIR=/srv/www \
    NODE_PATH=/usr/lib/node_modules:/usr/local/lib/node_modules:/usr/local/share/.config/yarn/global/node_modules \
    NPM_CONFIG_SPIN=false \
    NPM_CONFIG_PROGRESS=false \
    SRC_DIR=/src \
    NEW_RELIC_HOME=/srv/ \
    NEW_RELIC_LOG_LEVEL=info \
    NEW_RELIC_LICENSE_KEY=aaa \
    NEW_RELIC_APP_NAME=nodeapp \
    NEW_RELIC_NO_CONFIG_FILE=True

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="nodejs-base" \
      org.label-schema.description="This service provides a base nodejs platform." \
      org.label-schema.architecture="x86_64" \
      org.label-schema.distribution="Alpine Linux" \
      org.label-schema.distribution-version="%%UPSTREAM%%" \
      info.humanitarianresponse.nodejs="$NODE_VERSION" \
      info.humanitarianresponse.npm="$NPM_VERSION" \
      info.humanitarianresponse.yarn="$YARN_VERSION"

RUN set -x && apk update \
  && apk upgrade \
  && apk add --no-cache \
        libstdc++ \
  && apk add --no-cache \
        curl \
        git \
  && apk add --no-cache --virtual .build-deps \
        bash \
        binutils-gold \
        build-base \
        gnupg \
        linux-headers \
        perl \
        python2 \
  # gpg keys listed at https://github.com/nodejs/node#release-team
  && for key in \
    4ED778F539E3634C779C87C6D7062848A1AB005C \
    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    74F12602B6F1C4E913FAA37AD3A89613643B6201 \
    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600 \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
    C82FA3AE1CBEDC6BE46B9360C43CEC45C17AB93C \
    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    A48C2BEE680E841632CD4E44F07496B3EB3C1762 \
    108F52B48DB57BB0CC439B2997B01419BD92F80A \
    B9E2F5981AA6E0CD28160D9FF13993A75599653C \
  ; do \
    gpg --keyserver pool.sks-keyservers.net --recv-keys $key ; \
  done \
  && curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION.tar.xz" \
  && curl -SLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
  && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
  && grep " node-v$NODE_VERSION.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
  && tar -xf "node-v$NODE_VERSION.tar.xz" \
  && cd "node-v$NODE_VERSION" \
  && ./configure --prefix=/usr \
  && make -j$(getconf _NPROCESSORS_ONLN) \
  && make install \
  && cd .. \
  && rm -Rf "node-v$NODE_VERSION" \
  && rm "node-v$NODE_VERSION.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt \
  && npm install -g yarn \
  && yarn global add \
        grunt-cli \
        newrelic \
  && yarn cache clean \
  && apk del .build-deps \
  && rm -rf \
        /usr/lib/node_modules/npm/man \
        /usr/lib/node_modules/npm/doc \
        /usr/lib/node_modules/npm/html \
        /usr/lib/node_modules/npm/scripts \
        /tmp \
  &&  rm -rf /var/cache/apk/* \
  &&  mkdir -p /tmp \
  &&  chmod 1777 /tmp \
  &&  mkdir -p ${SRC_DIR} ${NODE_APP_DIR} \
  &&  cp -a /usr/local/share/.config/yarn/global/node_modules/newrelic/newrelic.js /srv
