FROM unocha/alpine-base-s6:%%UPSTREAM%%

# Parse arguments for the build command.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="postgis" \
      org.label-schema.description="This service provides a postgresql service" \
      info.humanitarianresponse.postgresql=$VERSION

ENV LANG=en_US.utf8 \
    PGDATA=/var/lib/pgsql \
    PG_CONFIG_FILE=/etc/pgsql/postgresql.conf \
    PGSQL_DB=testdb \
    PGSQL_USER=testuser \
    PGSQL_PASS=testpass

COPY fix_pgsql_dirs pg_hba.conf postgresql.conf recovery run_postgres /tmp/

RUN apk add \
        postgresql \
        postgresql-client \
        postgresql-contrib && \
    mkdir -p /etc/services.d/postgres /etc/fix-attrs.d /etc/pgsql /run/postgresql && \
    mv /tmp/fix_pgsql_dirs /etc/fix-attrs.d/ && \
    mv /tmp/run_postgres /etc/services.d/postgres/run && \
    mv /tmp/pg_hba.conf /etc/pgsql/ && \
    mv /tmp/postgresql.conf /etc/pgsql/ && \
    mv /tmp/recovery /etc/pgsql/ && \
    touch /etc/pgsql/pg_ident.conf && \
    rm -rf /var/cache/apk/*

ENTRYPOINT ["/init"]

CMD []

EXPOSE 5432

VOLUME ["/var/lib/pgsql"]
