
FROM unocha/alpine-base-s6:%%UPSTREAM%%

# Parse arguments for the build command.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="alpine-redis" \
      org.label-schema.description="This service provides a redis platform." \
      info.humanitarianresponse.redis=$VERSION

COPY run_redis redis.conf /

RUN apk add --update-cache redis && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /etc/redis /etc/services.d/redis && \
    mv /run_redis /etc/services.d/redis/run && \
    mv /etc/redis.conf /etc/redis.conf.ini && \
    mv /redis.conf /etc/redis/

EXPOSE 6379

VOLUME ["/var/log/redis", "/var/lib/redis"]

# Let's do an internal health check, eh?
HEALTHCHECK --interval=60s --timeout=5s \
      CMD redis-cli PING
