FROM python:%%UPSTREAM%%

MAINTAINER UN-OCHA Operations <ops+docker@humanitarianresponse.info>

# Parse arguments for the build command.
ARG VERSION
ARG VCS_URL
ARG VCS_REF
ARG BUILD_DATE

ENV CURATOR_VERSION ${VERSION}
ENV CURATOR_UID 555
ENV CURATOR_GID 555

# A little bit of metadata management.
# See http://label-schema.org/
LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vendor="UN-OCHA" \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.name="curator" \
      org.label-schema.description="This service provides the elasticsearch curator." \
      org.label-schema.architecture="x86_64" \
      org.label-schema.distribution="Debian Linux" \
      org.label-schema.distribution-version="8.5" \
      info.humanitarianresponse.curator=${VERSION}

RUN pip install --quiet elasticsearch-curator==${CURATOR_VERSION} && \
    groupadd -r -g ${CURATOR_GID} curator && \
    useradd -r -g curator -u ${CURATOR_UID} curator && \
    mkdir -p /etc/curator

ENTRYPOINT [ "/usr/local/bin/curator", "--config", "/etc/curator/curator.yml" ]
