include ../../Makefile.conf

IMAGE=curator

PYTHON=python:2.7-slim
UPSTREAM=2.7-slim
VERSION=$$(VERSION))
EXTRAVERSION=$$(EXTRAVERSION))

all: template build tag clean_images

mrproper: clean_images clean
